### PR TITLE
Updating theatre-societe-biblio according to #32 and #33

### PR DESCRIPTION
**Pull request by mrivoal**
Deleting:
- `Maison d’édition`  and `Date` from `Chapitre d’ouvrage`,
- `Maison d’édition` from `Article de périodique`
Adding:
- `Maison d’édition` to `Revue`
Also fixing typo in:
- `Editeur scientifique`, resulting in new properties for `Edition (critique)` and `Livre`.

@cschuwey, you need to check those changes on http://salsah-test.unil.ch/. 
(`salsah-gui:gui-order` is on the way)

### CODE REVIEW

**Comment by cschuwey** [comment]
Thanks for the changes. I can’t see them on salsah-test, is that normal ?

**Comment by mrivoal** [comment]
@cschuwey sorry. Now, you can check this on http://salsah-test.unil.ch/.

**Comment by cschuwey** [comment]
Sorry, I still don’t see the modifications (there is still a « maison d’édition » in « Chapitre d’ouvrage »).

**Comment by mrivoal** [comment]
Maybe try to empty your cache?

**Comment by cschuwey** [comment]
Works now. Everthing is perfect, except : 

I don’t understand the présence of both « Editeur scientifique » and « Auteur / éditeur scientifique » in « Édition critique ». Only one of those is needed.

**Comment by mrivoal** [comment]
Which one makes more sense to you for `Edition critique`? 
And you don't mind having both for `Livre`? 

Let me know and I will do the changes. Right after, I will merge this PR with `master branch` so that you can also see the changes in `salsah-gui:gui-order`.

**Comment by cschuwey** [comment]
For Livre it makes sense, as you can have a book with both an author and an editor. 

For edition critique, the best would be « Editeur scientifique » and delete the « Auteur / éditeur scientifique » from it. I will then rename « Auteur / éditeur scientifique » with just « Auteur » in biblio. 

Excited to see the guiOrder improvement ! THANKS.

**Comment by mrivoal** [comment]
All things considered, I think we should keep `Edition` with the property `Auteur / éditeur scientifique`. If we choose not to, then the best way to do so would be:
- either to consider that an `Edition` is not  a subclass of `Publication`
- or to remove the property `Auteur / Éditeur (édition critique)` from the class `Document` and make it applied locally to each of its subclasses (`Manuscrit`, `Publication`, `Book`, etc.). 

In either way, this will prevent users from searching for an author for all these subclasses by using the generic `Document` class and its `Auteur / éditeur scientifique` property. I don't think it would be very convenient.

So I would suggest to stick with the property `Auteur / éditeur scientifique` for `Edition` and deleting the `Editeur scientifique` one.

**Comment by cschuwey** [comment]
I understand the problem and I agree with your explanation and solution. To me, it seems that Edition is definitely a subclass of publication. Auteur applies everywhere except in « Édition critique »… does it really worth it to apply it locally to each subclass ? Isn’t a labeling question ? Technically, the « éditeur scientifique » is an author ; it is just unclear for users to call it another, because they risk thinking that this is the author of the original document (Voltaire in the case of a critical edition of its correspondence). 

What do you think about this status quo solution (while deleting « Editeur scientifique ») ?
Christophe

**Comment by mrivoal** [comment]
Actually, I ran some tests and discovered a functionnality of Knora that I didn't know. 
I managed to create a property `Editeur scientifique de l'édition` which is a subproperty of `Auteur` (I have updated the label of this one consequently) and is specifically attached to `Edition`. 

I have to check with the Basel team on this functionnality (is it really the expected behaviour?) but right now, you can have a look at it. It is exactly what i think you wanted.

By the way, `salsah-gui:gui-order` properties have been updated. As you will see, it does not always comply with what you wished for theatre-societe-biblio-onto.ttl (because some properties are attached to parent classes and it is difficult to managed both the parent class and the children class with only one `salsah-gui:gui-order` property), but hopefully it is not too far from what you wanted. Let me know if it is satisfactory as is (or nor).

**Comment by cschuwey** [comment]
That is simply amazing – Thanks so much for all the work !

I just ran through the fields and objects and gui:Order seems perfect. Thanks for the headache ! One minor thing, if it can be changed easily :
– Article de périodique : « numéro » and « volume » are too far from each other. Ideally, if « numero » could be anywhere after Revue (or better, after Date), that would be perfect. 

Thanks again. May I show the team the « Salsah-test » version for final validation ?

Christophe

**Comment by cschuwey** [comment]
Ok for the test.

For Article de périodique, the second solution would be perfect. 

Thanks again !
Christophe

**Comment by mrivoal** [comment]
Ok. Will do.

**Pull request merged**
